# Generated by Django 4.1.6 on 2023-02-02 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_movil', models.IntegerField(unique=True, verbose_name='Nombre de la Instalación')),
                ('mensaje', models.CharField(max_length=100)),
                ('cant_personas', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cant_bici', models.IntegerField()),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.transporte', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
            },
        ),
        migrations.CreateModel(
            name='ReservaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_movil', models.IntegerField(unique=True, verbose_name='Nombre de la Instalación')),
                ('mensaje', models.CharField(max_length=100)),
                ('cant_personas', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('fecha', models.DateField()),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Gastronomía',
                'verbose_name_plural': 'Gastronómicas',
            },
        ),
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_movil', models.IntegerField(unique=True, verbose_name='Nombre de la Instalación')),
                ('mensaje', models.CharField(max_length=100)),
                ('cant_mayores', models.IntegerField()),
                ('cant_menores', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('cant_habitaciones', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Alojamiento',
                'verbose_name_plural': 'Alojamientos',
            },
        ),
    ]
