# Generated by Django 4.1.6 on 2023-02-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservahotel',
            name='mensaje',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reservarestaurante',
            name='mensaje',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reservatransporte',
            name='mensaje',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
